FROM ubuntu:latest
COPY . /home/app_java

# install jdk8
RUN apt-get update && apt-get install -y openjdk-8-jdk
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
RUN export  JAVA_HOME

# install maven
RUN apt install -y maven
ENV MAVEN_HOME /usr/share/maven
RUN export MAVEN_HOME

# run app
WORKDIR /home/app_java/employee/target
CMD ["java", "-jar", "spring-boot-docker-mysql.jar"]

EXPOSE 8090









